[package]
name = "ppm"
version = "0.1.0"
authors = ["Clément Depraz <clem.depraz@gmail.com>"]
edition = "2018"

[lib]
name = "ppm"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
